SRC_PATH = r'D:\HCMUS\Nam3\HK2\BaoMat-CSDL\LAB\Lab4\src'

WINDOW_WIDTH_LOGIN = 331
WINDOW_HEIGHT_LOGIN = 421

IMAGE_USER_LOGIN = "images/user.png"

WINDOW_WIDTH_QLLOPHOC = 1219
WINDOW_HEIGHT_QLLOPHOC = 871

QUANLYLOPHOC_NAME_COLUMN_LOPHOC = ["MALOP", "TENLOP", "MANV"]
QUANLYLOPHOC_NAME_COLUMN_SINHVIEN = ["MASV", "HOTEN", "NGAYSINH", "DIACHI", "MALOP", "TENDN", "MATKHAU"]

NHAPDIEM_NAME_COLUMN_SINHVIEN_LOPHOC = ["MASV", "HOTEN", "MALOP", "MANV"]
NHAPDIEM_NAME_COLUM_SINHVIEN_HOCPHAN = ["MASV", "MAHP", "TENHP", "SOTC", "DIEMTHI"]

NHANVIEN_COLUMN = ['MANV', 'HOTEN', 'EMAIL', 'LUONG', 'TENDN', 'MATKHAU', 'PUBKEY']

WINDOW_WIDTH_INFOR_ACCOUNT = 687
WINDOW_HEIGHT_INFOR_ACCOUNT = 461


CONFIG_DATABASE = {
    'DRIVER': 'SQL SERVER',
    'SERVER': 'Hofin504',
    'DATABASE': 'QLSVNhom'
}

# global variable

username = 'user1'
password = '1231'
manv = 'NV01'

# cipher 
RSA_BITS = 2048

