USE QLSVNHOM
GO 



if 'SP_INS_PUBLIC_ENCRYPT_NHANVIEN' in (select name from sys.procedures) 
	drop procedure SP_INS_PUBLIC_ENCRYPT_NHANVIEN
go

CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN (
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARBINARY(MAX), 
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX),
	@PUB VARBINARY(MAX)
)
AS 
BEGIN 
	INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY) 
	VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @PUB)
END 
GO

if 'SP_SEL_PUBLIC_ENCRYPT_NHANVIEN' in (select name from sys.procedures) 
	drop procedure SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
go

CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN(
	@TENDN NVARCHAR(100),
	@MK VARBINARY(MAX)
)
AS 
BEGIN

	SELECT 
		MANV, 
		HOTEN, 
		EMAIL, 
		LUONG,
		PUBKEY
	FROM NHANVIEN
	WHERE TENDN = @TENDN AND MATKHAU = @MK

END
GO

CREATE PROCEDURE SP_UPDATE_DIEM(
	@MASV VARCHAR(20), 
	@MAHP VARCHAR(20),
	@DIEM VARBINARY(MAX),
	@MANV VARCHAR(20)
)
AS 
BEGIN
	UPDATE BANGDIEM
	SET DIEMTHI = @DIEM
	WHERE @MASV = MASV AND @MAHP = MAHP
END 

GO 

CREATE PROCEDURE SP_SEL_DIEM (
	@MASV VARCHAR(20)
)
AS
BEGIN
	SELECT 
		BANGDIEM.MASV, BANGDIEM.MAHP, HOCPHAN.TENHP, HOCPHAN.SOTC, DIEMTHI
	FROM 
		BANGDIEM JOIN SINHVIEN ON BANGDIEM.MASV = SINHVIEN.MASV
		JOIN HOCPHAN ON HOCPHAN.MAHP = BANGDIEM.MAHP
	WHERE SINHVIEN.MASV = @MASV 
END
GO 