CREATE DATABASE QLSVNhom;
GO 
USE QLSVNhom;
GO 

CREATE TABLE SINHVIEN (
	MASV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL UNIQUE, 
	MATKHAU VARBINARY(20),
	CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
)

CREATE TABLE NHANVIEN (
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL UNIQUE,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARBINARY(MAX),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)

CREATE TABLE LOP (
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),

	CONSTRAINT PK_LOP_MALOP PRIMARY KEY (MALOP)
)

CREATE TABLE HOCPHAN (
	MAHP VARCHAR(20),
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT,
	
	CONSTRAINT PK_HOCPHAN_MAHP PRIMARY KEY (MAHP)
)

CREATE TABLE BANGDIEM (
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX), 
	
	CONSTRAINT PK_BANGDIEM_MASV_MAHP PRIMARY KEY (MASV, MAHP)
)

GO 

-- SINHVIEN(MALOP) -> LOP(MALOP)
ALTER TABLE SINHVIEN 
ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP)
REFERENCES LOP (MALOP)

-- BANGDIEM(MASV) -> SINHVIEN(MASV)
ALTER TABLE BANGDIEM 
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MASV)
REFERENCES SINHVIEN(MASV)

-- BANGDIEM(MAHP) -> HOCPHAN(MAHP)
ALTER TABLE BANGDIEM 
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY (MAHP)
REFERENCES HOCPHAN(MAHP)

GO 

--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV01', N'Nguyễn Văn Một',	'vanmot@gmail.com', 1000, N'user1', '1231';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV02', N'Nguyễn Văn Hai',	'vanhai@gmail.com', 2000, N'user2', '1232';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV03', N'Nguyễn Văn Ba',	'vanba@gmail.com',	3000, N'user3', '1233';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV04', N'Nguyễn Văn Tư',	'vantu@gmail.com',	4000, N'user4', '1234';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV05', N'Nguyễn Văn Năm',	'vannam@gmail.com', 5000, N'user5', '1235';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV06', N'Nguyễn Văn Sáu',	'vansau@gmail.com', 6000, N'user6', '1236';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV07', N'Nguyễn Văn Bảy',	'vanbay@gmail.com', 7000, N'user7', '1237';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV08', N'Nguyễn Văn Tám',	'vantam@gmail.com', 8000, N'user8', '1238';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV09', N'Nguyễn Văn Chín',	'vanchin@gmail.com', 9000, N'user9', '1239';
--EXECUTE SP_INS_PUBLIC_NHANVIEN 'NV10', N'Nguyễn Văn Mười',	'vanmuoi@gmail.com', 10000, N'user10', '12310';


INSERT INTO LOP VALUES ('LOP01', N'Lớp Toán 1', 'NV01')
INSERT INTO LOP VALUES ('LOP02', N'Lớp Văn 1',	'NV02')
INSERT INTO LOP VALUES ('LOP03', N'Lớp Anh 1',	'NV03')
INSERT INTO LOP VALUES ('LOP04', N'Lớp Lý 1',	'NV04')
INSERT INTO LOP VALUES ('LOP05', N'Lớp Hóa 1',	'NV05')
INSERT INTO LOP VALUES ('LOP06', N'Lớp Sinh 1',	'NV06')
INSERT INTO LOP VALUES ('LOP07', N'Lớp Sử 1',	'NV07')
INSERT INTO LOP VALUES ('LOP08', N'Lớp Địa 1',	'NV08')
INSERT INTO LOP VALUES ('LOP09', N'Lớp Tin 1',	'NV09')
INSERT INTO LOP VALUES ('LOP10', N'Lớp GDCD 1',	'NV10')

GO 
DECLARE @i INT = 1, @j INT = 1;
WHILE @i <= 10 -- Duyệt qua 10 lớp
BEGIN
    SET @j = 1;
    WHILE @j <= 30 -- Mỗi lớp có 30 sinh viên
    BEGIN
        INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
        VALUES (
            'SV' + RIGHT('000' + CAST(((@i - 1) * 30 + @j) AS VARCHAR), 3),
            N'Sinh viên ' + CAST(((@i - 1) * 30 + @j) AS NVARCHAR),
            DATEADD(DAY, -(((@i - 1) * 30 + @j) * 50) % 10000, GETDATE()),
            N'Địa chỉ ' + CAST(((@i - 1) * 30 + @j) AS NVARCHAR),
            'LOP' + RIGHT('00' + CAST(@i AS VARCHAR), 2),
            N'sv' + CAST(((@i - 1) * 30 + @j) AS NVARCHAR),
            CONVERT(VARBINARY, HASHBYTES('SHA1', 'password' + CAST(((@i - 1) * 30 + @j) AS NVARCHAR)))
        );
        SET @j = @j + 1;
    END;
    SET @i = @i + 1;
END;

GO

select * from sinhvien

go 
DECLARE @k INT = 1;
WHILE @k <= 50 -- 50 học phần
BEGIN
    INSERT INTO HOCPHAN (MAHP, TENHP, SOTC)
    VALUES (
        'HP' + RIGHT('000' + CAST(@k AS VARCHAR), 3),
        N'Học phần ' + CAST(@k AS NVARCHAR),
        (RAND() * 4 + 1)
    );
    SET @k = @k + 1;
END;

GO

select * from hocphan 

go 
DECLARE @m INT = 1, @n INT = 1;
WHILE @m <= 300 -- 300 sinh viên
BEGIN
    SET @n = 1;
    WHILE @n <= 50 -- Mỗi sinh viên có 50 học phần
    BEGIN
        INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI)
        VALUES (
            'SV' + RIGHT('000' + CAST(@m AS VARCHAR), 3),
            'HP' + RIGHT('000' + CAST(@n AS VARCHAR), 3),
            NULL
        );
        SET @n = @n + 1;
    END;
    SET @m = @m + 1;
END;

GO

select * from BANGDIEM